#on:
  #schedule:
    #  5:30 and 17:30 UTC
    #  - cron:  '30 5,17 * * *'
    # * is a special character in YAML so you have to quote this string
    # Every 10 minutes
    #- cron:  '*/10 * * * *'
on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Every time
        run: ls > test.txt