on:
  schedule:
    #  5:30 and 17:30 UTC
    #  - cron:  '30 5,17 * * *'
    # * is a special character in YAML so you have to quote this string
    # Monthly on 1st at 2pm est
    - cron:  '0 18 1 * *'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - shell: bash
        env:
          GOOGLEFONTSAPI: ${{ secrets.GOOGLEFONTSAPI }}
        run: |
          curl "https://www.googleapis.com/webfonts/v1/webfonts?key=${GOOGLEFONTSAPI}" > src/fonts.json
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fetch fonts.json (Google Fonts json listing) from action
