on:
  schedule:
    #  5:30 and 17:30 UTC
    #  - cron:  '30 5,17 * * *'
    # * is a special character in YAML so you have to quote this string
    # Every 10 minutes
    - cron:  '*/10 * * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Every time
        run: date